config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: %i[passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: %i[registrations passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :order_details, only: %i[update]
    resources :orders, only: %i[show index update]
    resources :customers, only: %i[show index edit update]
    resources :categories, only: %i[index edit create update destroy]
    resources :items, only: %i[index new show edit create update]
    get "/" => "homes#top"
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about', to:'homes#about', as:'about'
    delete "carts/destroy_all" => "carts#destroy_all"
    resources :items, only: %i[index show]
    resources :addresses, only: %i[index edit create destroy update]
    resources :carts, only: %i[index create destroy update]
    # resources :customers, only: %i[show update edit]
    resources :orders, only: %i[index show new create] do
      collection do
        get 'confirm'
        get 'complete'
      end
    end

    patch "customers/information/edit" => "customers#update"
    patch "customers/withdraw" => "customers#withdraw"
    get "customers/unsubscribe" => "customers#unsubscribe"
    get "customers/information/edit" => "customers#edit"
    get "customers/my_page" => "customers#show"
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached:image
  belongs_to :category
  has_many :carts, dependent: :destroy
  has_many :order_details, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :image, presence: true

  def taxin_price
        price*1.1
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_item, only: [:show, :edit, :update]
  before_action :set_categories, only: [:new, :create, :edit, :update]

  def new
    @item = Item.new
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_items_path, notice: "商品を登録しました"
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to admin_items_path, notice: "商品を編集しました"
    else
      flash[:alert] = "保存に失敗しました"
      render :edit
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def set_categories
    @categories = Category.all
  end

  def item_params
    params.require(:item).permit(:price, :name, :description, :image, :category_id, :is_active)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_is_active.html.erb
<%= form_with model: item, url: admin_items_path, method: :post do |f| %>
<tr>
  <th>
    <label for="item_is_active" class="d-flex align-items-center">
      販売ステータス
    </label>
  </th>
  <td class="p-1">
    <%= f.radio_button :is_active, true %>
    <%= f.label :is_active_true, '販売中' %>
    <%= f.radio_button :is_active, false %>
    <%= f.label :is_active_false, '販売停止中' %>
  </td>
</tr>
<% end %>

app/views/admin/items/_status.html.erb
<% if item.is_active == true %>
  <span style="color: green; font-weight: bold;">販売中</span>
<% else %>
  <span style="color: gray; font-weight: bold;">停止中</span>
<% end %>

app/views/admin/items/edit.html.erb
<%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="container-fluid">
  <%= flash[:notice] %>
  <div class="row my-3 justify-content-center">
    <div class="col-2 m-4">
      <h2 class="mb-2 text-center" style="font-size: 1.3rem; background-color: #f5deb3;">商品編集</class>
      </div>
    </div>
    <div class="row my-3 justify-content-center">
      <div class="col-5">
        <%= form_with model: @item, url: admin_item_path do |f| %>
          <table>
            <tr>
              <th>商品画像</th>
              <td class="pt-1 pb-1">
                <%= f.file_field :image %>
              </td>
            </tr>
            <tr>
              <th>商品名</th>
              <td class="p-1">
                <%= f.text_field :name %>
              </td>
            </tr>
            <tr>
              <th class="pt-3" style="vertical-align: top;">商品説明</th>
              <td>
                <%= f.text_area :description, class: "form-control", style: 'height: 150px;color: #6c757d;', placeholder: 'ここに説明文を記述します', onfocus: "this.style.color='black';" %>
              </td>
            </tr>
            <tr>
              <th>ジャンル</th>
              <td class="p-1">
                <%= f.collection_select :category_id, Category.all, :id, :name %>
              </td>
            </tr>
            <tr>
              <th>税抜価格</th>
              <td class="p-1">
                <%= f.text_field :price, class: "form-control", style: 'color: #6c757d;', placeholder: '1000', onfocus: "this.style.color='black';" %><td>円</td>
              </td>
            </tr>
            <%= render 'is_active', item: @item %>
          </table>
          <div class="row my-3 justify-content-center">
            <%= f.submit "変更を保存", class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container mx-auto">
  <%= flash[:notice] %>
  <div class="row my-3 justify-content-center">
    <div class="col-10">
      <div class="d-flex justify-content-between align-items-center mb-3">
        <h2 class="col-2 mb-0 text-center px-2" style="font-size: 1.3rem; background-color: #f5deb3;">商品一覧</h2>
        <%= link_to new_admin_item_path, class: 'btn btn-outline-secondary rounded-circle shadow-sm' do %>
          <i class="fa-solid fa-plus"></i>
        <% end %>
      </div>
      <table class="table table-bordered">
        <thead>
          <tr class="table-active">
            <th class="p-3">商品ID</th>
            <th class="p-3">商品名</th>
            <th class="p-3">税抜価格</th>
            <th class="p-3">ジャンル</th>
            <th class="p-3">ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td class="p-3"><%= item.id %></td>
              <td class="p-3">
                <%= link_to admin_item_path(item.id), class: 'text-decoration-underline text-dark' do %>
                  <%= item.name %>
                <% end %>
              </td>
              <td class="p-3"><%= number_to_currency((item.price).floor, unit: '', delimiter: ',') %></td>
              <td class="p-3"><%= item.category.name %></td>
              <td class="p-3"><%= render 'status', item: item %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="d-flex justify-content-center mt-3">
        <%= paginate @items %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="container-fluid">
  <div class="row my-3 justify-content-center">
    <div class="col-2 m-4">
      <h2 class="mb-2 text-center" style="font-size: 1.3rem; background-color: #f5deb3;">商品新規登録</h2>
    </div>
  </div>
  <div class="row my-3 justify-content-center">
    <div class="col-5">
      <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
        <div class="col-12 ml-4">
          <table>
            <tr>
              <th>商品画像</th>
              <td class="pt-1 pb-1">
                <%= f.file_field :image, accept: "image/*", class: "form-control border-0" %> <!-- border-0を追加 -->
              </td>
            </tr>
            <tr>
              <th>商品名</th>
              <td class="p-1">
                <%= f.text_field :name, class: "form-control", style: 'color: #6c757d;', placeholder: '商品名', onfocus: "this.style.color='black';" %>
              </td>
            </tr>
            <tr>
              <th class="pt-3" style="vertical-align: top;">商品説明</th>
              <td class="p-1">
                <%= f.text_area :description, class: "form-control", style: 'height: 150px;color: #6c757d;', placeholder: 'ここに説明文を記述します', onfocus: "this.style.color='black';" %>
              </td>
            </tr>
            <tr>
              <th>ジャンル</th>
              <td class="p-1">
                <%= f.select :category_id, options_for_select(Category.all.collect { |c| [c.name, c.id] }), prompt: false, class: "form-control" %>
              </td>
            </tr>
            <tr>
              <th>税抜価格</th>
              <td class="p-1">
                <%= f.text_field :price, class: "form-control", style: 'color: #6c757d;', placeholder: '1000', onfocus: "this.style.color='black';" %><td>円</td>
              </td>
            </tr>
          </table>
        </div>
        <div class="row my-3 justify-content-center">
          <%= f.submit "新規登録", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="container-fluid">
  <div class="row my-3 justify-content-center">
    <div class="col-9">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <h2 class="text-center px-4 g" style="font-size: 1.3rem; background-color: #f5deb3;">
          商品詳細
        </h2>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-4 d-flex justify-content-center mt-5">
        <%= image_tag @item.image, size: '250x200' %>
      </div>
      <div class="col-7 mt-5">
        <table class="table">
          <tr>
            <th class="p-3">商品名</th>
            <td class="p-3"><%= @item.name %></td>
          </tr>
          <tr>
            <th class="p-3">商品説明</th>
            <td class="p-3"><%= @item.description %></td>
          </tr>
          <tr>
            <th class="p-3">ジャンル</th>
            <td class="p-3"><%= @item.category.name %></td>
          </tr>
          <tr>
            <th class="p-3">
              税込価格<br>
              (税抜価格)
            </th>
            <td class="p-3">
              <%= number_to_currency((@item.price * 1.1).floor, unit: '', delimiter: ',') %>円
              (<%= number_to_currency(@item.price.floor, unit: '', delimiter: ',') %>円)
            </td>
          </tr>
          <tr>
            <th class="p-3">販売ステータス</th>
            <td class="p-3"><%= render 'status', item: @item %></td>
          </tr>
        </table>
        <%= link_to "編集する", edit_admin_item_path(@item), class: 'btn btn-success' %>
      </div>
    </div>
  </div>
</div>