config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: %i[passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: %i[registrations passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :order_details, only: %i[update]
    resources :orders, only: %i[show index update]
    resources :customers, only: %i[show index edit update]
    resources :categories, only: %i[index edit create update destroy]
    resources :items, only: %i[index new show edit create update]
    get "/" => "homes#top"
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about', to:'homes#about', as:'about'
    delete "carts/destroy_all" => "carts#destroy_all"
    resources :items, only: %i[index show]
    resources :addresses, only: %i[index edit create destroy update]
    resources :carts, only: %i[index create destroy update]
    # resources :customers, only: %i[show update edit]
    resources :orders, only: %i[index show new create] do
      collection do
        get 'confirm'
        get 'complete'
      end
    end

    patch "customers/information/edit" => "customers#update"
    patch "customers/withdraw" => "customers#withdraw"
    get "customers/unsubscribe" => "customers#unsubscribe"
    get "customers/information/edit" => "customers#edit"
    get "customers/my_page" => "customers#show"
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :carts, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: { message: "の入力は必須です", full_message:false}
  validates :last_name, presence: { message: "の入力は必須です" }
  validates :first_name_kana, presence: { message: "の入力は必須です" }
  validates :last_name_kana, presence: { message: "の入力は必須です" }
  validates :post_code,presence: { message: "の入力は必須です" }, length: { is: 7 }
  validates :address, presence: { message: "の入力は必須です" }
  validates :phone, presence: { message: "の入力は必須です" }, length: {minimum: 10, maximum: 11}, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 99999999999 },
format: { with: /\A[0-9]+\z/ }
  
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報を変更しました"
      redirect_to admin_customer_path
    else
      @customer = Customer.find(params[:id])
      flash[:fail] = "変更に失敗しました"
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :post_code, :address, :phone, :email, :is_active)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= flash[:fail] %>
<div class="container mx-auto container-fluid">
  <div class="row my-3 justify-content-center">
    <div class="col-10 px-sm-0">
      <div style="display: flex; align-items: center; justify-content: space-between;">
         <span class="mb-3 pr-3 pl-3" style="font-size: 1.3rem; background-color: #ECECEC; font-weight: bold;"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</span>
        <div style="text-align: right;">
        </div>
      </div>


<%= form_with model: @customer, url: admin_customer_path, method: :patch do |f| %>
  <table>
    <tr>
      <td class="pb-2">会員ID</td>
      <td class="pb-2 pl-5"><%= @customer.id %></td>
    </tr>
    <tr>
      <td class="pb-2">氏名</td>
      <td class="pb-2 pl-5">
        <%= f.text_field :last_name, class: 'form-control border border-secondary' %>
      </td>
      <td class="pl-4 pb-2 pl-2">
        <%= f.text_field :first_name, class: 'form-control border border-secondary' %>
      </td>
    </tr>
    <tr>
      <td class="pb-2">フリガナ</td>
      <td class="pb-2 pl-5">
        <%= f.text_field :last_name_kana, class: 'form-control border border-secondary' %>
      </td>
      <td class="pl-4 pb-2 pl-2">
        <%= f.text_field :first_name_kana, class: 'form-control border border-secondary' %>
      </td>
    </tr>
    <tr>
      <td class="pb-2">郵便番号</td>
      <td class="pb-2 pl-5"><%= f.text_field :post_code, class: 'form-control border border-secondary' %></td>
    </tr>
    <tr>
      <td class="pb-2">住所</td>
      <td colspan="2" class="pb-2 pl-5"><%= f.text_field :address, class: 'form-control border border-secondary' %></td>
    </tr>
    <tr>
      <td class="pb-2">電話番号</td>
      <td class="pb-2 pl-5"><%= f.text_field :phone, class: 'form-control border border-secondary' %></td>
    </tr>
    <tr>
      <td class="pb-2">メールアドレス</td>
      <td class="pb-2 pl-5"><%= f.text_field :email, class: 'form-control border border-secondary' %></td>
    </tr>
      <td class="pb-2">会員ステータス</td>
      <td class="pb-2 pl-5">
        <%= f.radio_button :is_active, :true %>
        <%= f.label :is_active, "有効"%>
        <%= f.radio_button :is_active, :false, class: 'ml-4' %>
        <%= f.label :is_active, "退会", class: 'text-right' %>
      </td>
    <tr>
      <td class="pb-2"></td>
      <td class="pb-2 pl-5"><%= f.submit "変更を保存", class: 'btn btn-success' %></td>
    </tr>
  </table>
<% end %>

    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container mx-auto container-fluid">
  <div class="row my-3 justify-content-center">
    <div class="col-10 px-sm-0">
      <div style="display: flex; align-items: center; justify-content: space-between;">
          <span class="pr-3 pl-3" style="font-size: 1.3rem; background-color: #ECECEC; font-weight: bold;">会員一覧</span>
        <div style="text-align: right;">
        </div>
      </div>


    <div class="col-12 mt-3">
      <table class="w-100" style="border-top: 2px solid gray; border-bottom: 2px solid gray;">
        <thead>
          <tr>
            <th class="table-active" style="padding: 10px; border-bottom:2px;">会員ID</th>
            <th class="table-active" style="padding: 10px; border-bottom:2px;">氏名</th>
            <th class="table-active" style="padding: 10px; border-bottom:2px;">メールアドレス</th>
            <th class="table-active" style="padding: 10px; border-bottom:2px;">ステータス</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% @customers.each do |customer| %>
          </tr>
          <td style="padding: 10px;"><%= customer.id %></td>
          <td style="padding: 10px;">
            <%= link_to admin_customer_path(customer) do %>
              <%= customer.last_name %><%= customer.first_name %>
            <% end %>
          </td>
          <td style="padding: 10px;"><%= customer.email %></td>
          <td style="padding: 10px;">
            <% if customer.is_active == true %>
              有効
            <% else %>
              退会
            <% end %>
          </td>
          <% end %>
        </tbody>
      </table>
          <div class="d-flex justify-content-center mt-3">
          <%= paginate @customers %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="container mx-auto container-fluid">
  <div class="row my-3 justify-content-center">
    <div class="col-8 px-sm-0">

       <div style="display: flex; align-items: center; justify-content: space-between;">
        <span class="px-3 my-3" style="font-size: 1.3rem; background-color: #ECECEC; font-weight: bold;"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</span>
      </div>

      <table class="mr-5">
        <tr>
          <td class="py-2">会員ID</td>
          <td style="padding-left: 100px;"><%= @customer.id %></td>
        </tr>
        <tr>
          <td class="py-2">氏名</td>
          <td style="padding-left: 100px;"><%= @customer.last_name %> <%= @customer.first_name %></td>
        </tr>
        <tr>
          <td class="py-2">フリガナ</td>
          <td style="padding-left: 100px;"><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
        </tr>
        <tr>
          <td class="py-2">郵便番号</td>
          <td style="padding-left: 100px;"><%= @customer.post_code %></td>
        </tr>
        <tr>
          <td class="py-2">住所</td>
          <td style="padding-left: 100px;"><%= @customer.address %></td>
        </tr>
        <tr>
          <td class="py-2">電話番号</td>
          <td style="padding-left: 100px;"><%= @customer.phone %></td>
        </tr>
        <tr>
          <td class="py-2">メールアドレス</td>
          <td style="padding-left: 100px;"><%= @customer.email %></td>
        </tr>
        <tr>
          <td class="py-2">会員ステータス</td>
          <td style="padding-left: 100px;">
            <% if @customer.is_active == true %>
              有効
            <% else %>
              退会
            <% end %>
          </td>
        </tr>
        <tr>
          <td class="py-4"></td>
          <td style="padding-left: 100px;"><%= link_to "編集する", edit_admin_customer_path, class: 'btn btn-success' %></td>
          <td class="px-5"><%= link_to "注文履歴一覧を見る", admin_path, class: 'btn btn-primary' %></td>
        </tr>
      </table>
    </div>
  </div>
</div>