config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: %i[passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: %i[registrations passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :order_details, only: %i[update]
    resources :orders, only: %i[show index update]
    resources :customers, only: %i[show index edit update]
    resources :categories, only: %i[index edit create update destroy]
    resources :items, only: %i[index new show edit create update]
    get "/" => "homes#top"
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about', to:'homes#about', as:'about'
    delete "carts/destroy_all" => "carts#destroy_all"
    resources :items, only: %i[index show]
    resources :addresses, only: %i[index edit create destroy update]
    resources :carts, only: %i[index create destroy update]
    # resources :customers, only: %i[show update edit]
    resources :orders, only: %i[index show new create] do
      collection do
        get 'confirm'
        get 'complete'
      end
    end

    patch "customers/information/edit" => "customers#update"
    patch "customers/withdraw" => "customers#withdraw"
    get "customers/unsubscribe" => "customers#unsubscribe"
    get "customers/information/edit" => "customers#edit"
    get "customers/my_page" => "customers#show"
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  validates :address, :post_code, :name, presence: true
  enum payment: { credit_card: 0, transfer: 1 }
  enum select_address: { my_address: 0, registered_address: 1, new_address: 2 }
  enum status: { waiting_payment: 0, checked_payment: 1, in_making: 2, ready: 3, finish: 4 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.status == 'checked_payment'
      @order.order_details.update(making_status: 1)
    else @order.status == 'waiting_payment'
      @order.order_details.update(making_status: 0)
    end
    flash[:notice] = "変更しました"
    redirect_back(fallback_location: root_path)
  end
  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/_item_list.html.erb
<!--注文詳細 製品ごとの表・金額内訳-->
<div class="row" style="position:relative">
    <div class="col-8">
      <table class="table border-top border-bottom">
        <thead>
          <tr>
            <th class="table-active">商品名</th>
            <th class="table-active">単価(税込)</th>
            <th class="table-active">数量</th>
            <th class="table-active">小計</th>
            <th class="table-active">製作ステータス</th>
            <th class="table-active"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% order_details.each do |order_detail| %>
          <tr>
          <td class="col-4"><%= order_detail.item.name %></td>
          <td class="col-2"><%= number_to_currency((order_detail.price * 1.1).floor, unit: '',delimiter: ',') %></td>
          <td><%= order_detail.quantity %></td>
          <td><%= number_to_currency((order_detail.price * 1.1 * order_detail.quantity).floor, unit: '',delimiter: ',') %></td>
          <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %>
          <td><%= f.select :making_status, OrderDetail.making_statuses.keys.map { |k| [OrderDetail.making_statuses_i18n[k], k] }, { selected: order_detail.making_status }, class: "form-control", style: "font-weight: bold;" %></td>
        　<td><%= f.submit '更新', class: 'btn btn-success' %></td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <!--テーブルを右下に固定したい-->
    <div class="table border-top border-bottom col-3 mb-3" style="position:absolute; bottom:0; right:0;">
      <table>
        <tr>
          <th class="col-sm-3" >商品合計</th>
          <td class="col-sm-2"><%= number_to_currency((order.total - order.fee).floor, unit: '',delimiter: ',') %></td>
        </tr>
        <tr>
          <th class="col-sm-3">送料</th>
          <td class="col-sm-2"><%= number_to_currency((order.fee).floor, unit: '',delimiter: ',') %></td>
        </tr>
        <tr>
          <th class="col-sm-3">請求金額合計</th>
          <td class="col-sm-2"><%= number_to_currency((order.total).floor, unit: '',delimiter: ',') %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/_order_info.html.erb
<!--注文・配送先情報のテーブル-->
<div class="container pt-3">
  <div class="my-3">
    <div class="row text-center">
      <div class="col-2">
        <h2 class="mb-2" style="font-size: 1.3rem; background-color: #f5deb3;">注文履歴詳細</h2>
      </div>
    </div>
  </div>
  <div class="row">
    <table>
      <tr>
        <th class="pr-4 pb-2">購入者</th>
        <td  class="pb-2">
          <%= link_to admin_customer_path(order.customer) do %>
            <%= order.customer.last_name %><%= order.customer.first_name %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th class="pr-4 pb-2">注文日</th>
        <td><%= order.created_at.strftime("%Y/%m/%d") %></td>
      </tr>
      <tr>
        <th class="pr-4 pb-2">配送先</th>
        <td>〒<%= order.post_code %> <%= order.address %><br>
          <%= order.name %>
        </td>
      </tr>
      <tr>
        <th class="pr-4 pb-2">支払方法</th>
        <td><%= order.payment_i18n %></td>
      </tr>
      <tr>
        <th class="pr-4 pb-2">注文ステータス</th>
          <td>
            <%= form_with model: order, url: admin_order_path, method: :patch do |f| %>
            <div class="d-flex">
              <%= f.select :status, Order.statuses.keys.map { |k| [Order.statuses_i18n[k], k] }, {}, class: "form-control w-75 mr-4", style: "font-weight: bold;" %>
                <%= f.hidden_field :id, :value => order.id %>
              <%= f.submit '更新', class: 'btn btn-success' %>
            </div>
            <% end %>
          </td>
      </tr>
    </table>
  </div>

app/views/admin/orders/show.html.erb
<%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= flash[:notice] %>
<!--上のテーブル 部分テンプレで呼び出す(_order_info.html.erb)-->
<%= render 'order_info', order: @order %>

<!--下の明細テーブル 部分テンプレートで作成-->
<%= render 'item_list', order_details: @order_details, order: @order %>