config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: %i[passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: %i[registrations passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :order_details, only: %i[update]
    resources :orders, only: %i[show index update]
    resources :customers, only: %i[show index edit update]
    resources :categories, only: %i[index edit create update destroy]
    resources :items, only: %i[index new show edit create update]
    get "/" => "homes#top"
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about', to:'homes#about', as:'about'
    delete "carts/destroy_all" => "carts#destroy_all"
    resources :items, only: %i[index show]
    resources :addresses, only: %i[index edit create destroy update]
    resources :carts, only: %i[index create destroy update]
    # resources :customers, only: %i[show update edit]
    resources :orders, only: %i[index show new create] do
      collection do
        get 'confirm'
        get 'complete'
      end
    end

    patch "customers/information/edit" => "customers#update"
    patch "customers/withdraw" => "customers#withdraw"
    get "customers/unsubscribe" => "customers#unsubscribe"
    get "customers/information/edit" => "customers#edit"
    get "customers/my_page" => "customers#show"
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :post_code, presence: true, length: { is: 7 }
  validates :name, presence: true, length: { in: 1..32 }
  validates :address, presence: true,  length: { minimum: 1 }

  def address_display
    '〒' + post_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
def sum_of_price
  item.taxin_price * quantity
end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :carts, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: { message: "の入力は必須です", full_message:false}
  validates :last_name, presence: { message: "の入力は必須です" }
  validates :first_name_kana, presence: { message: "の入力は必須です" }
  validates :last_name_kana, presence: { message: "の入力は必須です" }
  validates :post_code,presence: { message: "の入力は必須です" }, length: { is: 7 }
  validates :address, presence: { message: "の入力は必須です" }
  validates :phone, presence: { message: "の入力は必須です" }, length: {minimum: 10, maximum: 11}, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 99999999999 },
format: { with: /\A[0-9]+\z/ }
  
  
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached:image
  belongs_to :category
  has_many :carts, dependent: :destroy
  has_many :order_details, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :image, presence: true

  def taxin_price
        price*1.1
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  validates :address, :post_code, :name, presence: true
  enum payment: { credit_card: 0, transfer: 1 }
  enum select_address: { my_address: 0, registered_address: 1, new_address: 2 }
  enum status: { waiting_payment: 0, checked_payment: 1, in_making: 2, ready: 3, finish: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { stop_making: 0, waiting_make: 1, in_making: 2, finish: 3 }
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_item, only: [:show, :edit, :update]
  before_action :set_categories, only: [:new, :create, :edit, :update]

  def new
    @item = Item.new
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_items_path, notice: "商品を登録しました"
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to admin_items_path, notice: "商品を編集しました"
    else
      flash[:alert] = "保存に失敗しました"
      render :edit
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def set_categories
    @categories = Category.all
  end

  def item_params
    params.require(:item).permit(:price, :name, :description, :image, :category_id, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.status == 'checked_payment'
      @order.order_details.update(making_status: 1)
    else @order.status == 'waiting_payment'
      @order.order_details.update(making_status: 0)
    end
    flash[:notice] = "変更しました"
    redirect_back(fallback_location: root_path)
  end
  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
    # ログイン後のリダイレクト先
  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      root_path
    else
      root_path
    end
  end
    # ログアウト後のリダイレクト先
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      new_customer_session_path
    end
  end

    protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :email, :post_code, :address, :phone])
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "件のエラー") %>により保存されませんでした</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <script src="https://kit.fontawesome.com/f6eb215aef.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <!-- カスタムCSSの読み込み -->
    <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
        <!--ログイン時の名前表示-->
  <body>
    <header class="custom-header py-3">
        <div class="container-fluid px-5 d-flex justify-content-between align-items-center">
            <% if admin_signed_in? %>
                <div>
                    <%= link_to admin_path do %>
                        <%= image_tag 'logo.png', alt: 'NaganoCake Logo', class: 'logo-img' %>
                    <% end %>
                </div>
            <% elsif customer_signed_in? %>
                <div class="d-flex align-items-center">
                    <%= link_to root_path do %>
                        <%= image_tag 'logo.png', alt: 'NaganoCake Logo', class: 'logo-img' %>
                    <% end %>
                    <span class="ml-3 customer-greeting">ようこそ、<%= current_customer.last_name %>さん</span>
                </div>
            <% else %>
                <div>
                    <%= link_to root_path do %>
                        <%= image_tag 'logo.png', alt: 'NaganoCake Logo', class: 'logo-img' %>
                    <% end %>
                </div>
            <% end %>
        <!--ログイン別ヘッダー-->
            <div>
                <% if admin_signed_in? %>
                    <%= link_to '商品一覧', admin_items_path, class: 'text-decoration-none hover-effect mx-3' %>
                    <%= link_to '会員一覧', admin_customers_path, class: 'text-decoration-none hover-effect mx-3' %>
                    <%= link_to '注文履歴一覧', admin_path, class: 'text-decoration-none hover-effect mx-3' %>
                    <%= link_to 'ジャンル一覧', admin_categories_path, class: 'text-decoration-none hover-effect mx-3' %>
                    <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'text-decoration-none hover-effect mx-3' %>
                <% elsif customer_signed_in? %>
                    <%= link_to 'マイページ', customers_my_page_path, class: 'text-decoration-none hover-effect mx-3' %>
                    <%= link_to '商品一覧', items_path, class: 'text-decoration-none hover-effect mx-3' %>
                    <%= link_to 'カート', carts_path, class: 'text-decoration-none hover-effect mx-3' %>
                    <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: 'text-decoration-none hover-effect mx-3' %>
                <% else %>
                    <%= link_to 'About', about_path, class: 'text-decoration-none hover-effect mx-3' %>
                    <%= link_to '商品一覧', items_path, class: 'text-decoration-none hover-effect mx-3' %>
                    <%= link_to '新規登録', new_customer_registration_path, class: 'text-decoration-none hover-effect mx-3' %>
                    <%= link_to 'ログイン', new_customer_session_path, class: 'text-decoration-none hover-effect mx-3' %>
                <% end %>
            </div>
            <form action="#" class="search-form-5">
                <label>
                    <input type="text" placeholder="キーワードを入力">
                </label>
                <button type="submit" class="btn custom-btn" aria-label="検索">
                    <i class="fas fa-search"></i>
                </button>
            </form>
        </div>
    </header>
    <main class="main-content">
        <%= yield %>
    </main>
    <footer class="custom-footer py-3"></footer>
  </body>
</html>